import { normalizeFacilityType } from '@/lib/facility-types';
import { opportunityScore,sizeScore,ENERGY_FACTORS } from '@/lib/scoring';
import type { Prospect, SearchInput } from '@/lib/types';
import { liveDataForSeo,serverEnv } from '@/lib/env';
export interface DataForSeoProvider { search(input:SearchInput):Promise<unknown[]>; categories():Promise<string[]> }
export function normalizeDataForSeoResult(raw:any): Partial<Prospect> { const category=raw.category || raw.categories?.[0] || raw.type || ''; const facility_type=normalizeFacilityType(category); const address=raw.address || raw.address_info?.address || null; const city=raw.city || raw.address_info?.city || null; const state=raw.state || raw.address_info?.state || raw.address_info?.region || null; const latitude=Number(raw.latitude ?? raw.location?.latitude) || null; const longitude=Number(raw.longitude ?? raw.location?.longitude) || null; return {provider:'dataforseo',provider_place_id:String(raw.place_id || raw.cid || raw.id || '' ) || null,name:raw.title || raw.name || 'Unnamed facility',facility_type,source_category:category,address,city,state,postal_code:raw.zip || raw.address_info?.zip || null,latitude,longitude,website:raw.url || raw.website || null,phone:raw.phone || null,energy_factor:ENERGY_FACTORS[facility_type],size_score:0,opportunity_score:opportunityScore(facility_type,null),enrichment_status:'pending',prospect_status:'new',dataforseo_raw:raw}; }
const endpoint='https://api.dataforseo.com/v3/business_data/business_listings';
async function request(path:string,init?:RequestInit){const token=Buffer.from(`${serverEnv.DATAFORSEO_LOGIN}:${serverEnv.DATAFORSEO_PASSWORD}`).toString('base64');const response=await fetch(endpoint+path,{...init,headers:{Authorization:`Basic ${token}`,'Content-Type':'application/json',...(init?.headers||{})},signal:AbortSignal.timeout(20000)});if(!response.ok)throw new Error('DataForSEO is currently unavailable.');const body=await response.json();const task=body.tasks?.[0];if(task && task.status_code!==20000)throw new Error(task.status_message || 'DataForSEO request failed.');return body;}
export const dataForSeoProvider:DataForSeoProvider={async search(input){if(!liveDataForSeo)return [];const availableCategories=await this.categories();const validCategories=input.categories.filter(category=>availableCategories.includes(category)).slice(0,10);const task={location_coordinate:`${input.centerLatitude.toFixed(7)},${input.centerLongitude.toFixed(7)},${input.radiusKm}`,limit:Math.min(input.limit||250,1000),...(validCategories.length?{categories:validCategories}:{})};const body=await request('/search/live',{method:'POST',body:JSON.stringify([task])});return body.tasks?.[0]?.result?.[0]?.items || [];},async categories(){if(!liveDataForSeo)return [];const body=await request('/categories');return body.tasks?.[0]?.result?.map((x:any)=>x.category_name).filter(Boolean)||[];}};
