'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import type { AiFacilityResearch, Prospect } from '@/lib/types';
import { prospectSignalLabels, prospectSignals } from '@/lib/prospect-signals';
import ProspectMap from '@/components/ProspectMap';

const label = (value: string | null | undefined) => value?.replaceAll('_', ' ') || 'Unknown';
const signalFor = (prospect: Prospect) => prospectSignals(prospect);
const fitStyle: Record<string, string> = { high: 'bg-emerald-100 text-emerald-800', moderate: 'bg-amber-100 text-amber-800', low: 'bg-slate-200 text-slate-700', unknown: 'bg-slate-100 text-slate-600' };

function AiResearch({ research }: { research: AiFacilityResearch }) {
  return <section className="mt-6 border-t pt-5">
    <div className="flex items-center justify-between gap-3"><h3 className="font-semibold">AI facility research</h3><span className={`rounded-full px-2 py-1 text-xs font-semibold capitalize ${fitStyle[research.grid_switch_fit]}`}>{research.grid_switch_fit} outreach fit</span></div>
    <p className="mt-3 text-sm">{research.facility_summary}</p>
    <h4 className="mt-4 text-sm font-semibold">Source-backed findings</h4>
    {research.operating_evidence.length ? <ul className="mt-2 space-y-3 text-sm">{research.operating_evidence.map((item, index) => <li key={`${item.source_url}-${index}`}><div>{item.claim}</div><a className="text-xs text-teal-700 underline" href={item.source_url} target="_blank" rel="noreferrer">Open supporting source · {item.confidence} confidence</a></li>)}</ul> : <p className="mt-2 text-sm text-slate-500">No site-specific operating evidence was found.</p>}
    <h4 className="mt-4 text-sm font-semibold">Outreach angle</h4><p className="mt-1 text-sm">{research.outreach_angle}</p>
    <h4 className="mt-4 text-sm font-semibold">Questions to qualify the site</h4><ul className="mt-2 list-disc pl-5 text-sm space-y-1">{research.discovery_questions.map((question) => <li key={question}>{question}</li>)}</ul>
    {research.unknowns.length > 0 && <><h4 className="mt-4 text-sm font-semibold">Still unknown</h4><ul className="mt-2 list-disc pl-5 text-sm text-slate-600 space-y-1">{research.unknowns.map((unknown) => <li key={unknown}>{unknown}</li>)}</ul></>}
  </section>;
}

export default function Dashboard() {
  const [all, setAll] = useState<Prospect[]>([]); const [selected, setSelected] = useState<Prospect | null>(null);
  const [query, setQuery] = useState(''); const [city, setCity] = useState(''); const [type, setType] = useState(''); const [tier, setTier] = useState('');
  const [demo, setDemo] = useState(false); const [searching, setSearching] = useState(false); const [researchingIds, setResearchingIds] = useState<string[]>([]); const [notice, setNotice] = useState('');
  const loadProspects = useCallback(async () => { const response = await fetch('/api/prospects'); const payload = await response.json(); setAll(Array.isArray(payload.prospects) ? payload.prospects : []); setDemo(Boolean(payload.demo)); if (payload.error) setNotice(payload.error); }, []);
  useEffect(() => { void loadProspects(); }, [loadProspects]);
  const list = useMemo(() => all.filter((prospect) => (!city || prospect.city === city) && (!type || prospect.facility_type === type) && (!tier || signalFor(prospect).tier === tier) && `${prospect.name} ${prospect.address}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => signalFor(b).score - signalFor(a).score), [all, city, type, tier, query]);
  const metrics: [string, string | number][] = [['Listed facilities', list.length], ['Strong operating signals', list.filter((item) => signalFor(item).tier === 'strong_operating_signal').length], ['Listed 24/7', list.filter((item) => signalFor(item).is24Hour).length], ['AI researched', list.filter((item) => item.ai_research_status === 'complete').length]];

  async function findProspects() { setSearching(true); try { const response = await fetch('/api/prospects/search', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ centerLatitude: 40.8, centerLongitude: -77.8, radiusKm: 300, state: 'Pennsylvania', categories: ['industrial', 'manufacturing', 'warehouse'], limit: 250 }) }); const result = await response.json(); if (!response.ok) { setNotice(result.error || 'Live search failed.'); return; } setNotice(`Search complete: ${result.imported ?? 0} imported. Listings were automatically scored; use AI research for cited site-specific evidence.`); await loadProspects(); } catch { setNotice('Unable to reach the prospect search service.'); } finally { setSearching(false); } }
  async function researchOne(prospect: Prospect) { setResearchingIds((ids) => [...new Set([...ids, prospect.id])]); try { const response = await fetch(`/api/prospects/${prospect.id}/research`, { method: 'POST' }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'AI research failed.'); setAll((items) => items.map((item) => item.id === result.prospect.id ? result.prospect : item)); setSelected((item) => item?.id === result.prospect.id ? result.prospect : item); return true; } catch (cause) { setNotice(cause instanceof Error ? cause.message : 'AI research failed.'); return false; } finally { setResearchingIds((ids) => ids.filter((id) => id !== prospect.id)); } }
  async function researchTop3() { const candidates = list.filter((item) => item.ai_research_status !== 'complete').slice(0, 3); if (!candidates.length) { setNotice('The top filtered prospects have already been researched.'); return; } setNotice(`Researching ${candidates.length} facilities with cited web sources…`); const results = await Promise.all(candidates.map(researchOne)); setNotice(`AI research complete: ${results.filter(Boolean).length} succeeded, ${results.filter((result) => !result).length} failed.`); }
  const selectedSignals = selected ? signalFor(selected) : null; const isResearching = selected ? researchingIds.includes(selected.id) : false;

  return <main className="min-h-screen"><nav className="bg-[#101d29] text-white px-6 py-4 flex justify-between items-center"><div><b className="tracking-wide text-lg">GRIDSWITCH</b><span className="ml-3 text-sm text-slate-300">Prospecting Dashboard</span></div>{demo && <span className="rounded-full bg-slate-700 px-3 py-1 text-xs">Demo Data</span>}</nav><div className="p-5 max-w-[1800px] mx-auto">
    <div className="mb-4"><h1 className="text-xl font-bold">Find and research facilities worth a GridSwitch discovery call</h1><p className="text-sm text-slate-600 mt-1">Directory signals rank listings immediately. AI research adds cited, site-specific evidence and qualification questions; neither is an electricity-use estimate.</p></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-4">{metrics.map(([title, value]) => <div className="card p-4" key={title}><div className="text-xs uppercase text-slate-500">{title}</div><div className="text-2xl font-bold mt-1">{value}</div></div>)}</div>
    <div className="card p-3 flex gap-2 flex-wrap mb-4"><input className="control flex-1 min-w-48" placeholder="Search facility or address" value={query} onChange={(event) => setQuery(event.target.value)} /><select className="control" value={city} onChange={(event) => setCity(event.target.value)}><option value="">All cities</option>{[...new Set(all.map((item) => item.city).filter(Boolean))].map((item) => <option key={item}>{item}</option>)}</select><select className="control" value={type} onChange={(event) => setType(event.target.value)}><option value="">All facility types</option>{[...new Set(all.map((item) => item.facility_type).filter(Boolean))].map((item) => <option key={item} value={item!}>{label(item)}</option>)}</select><select className="control" value={tier} onChange={(event) => setTier(event.target.value)}><option value="">All prospect signals</option>{Object.entries(prospectSignalLabels).map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select><button className="control text-teal-800" disabled={researchingIds.length > 0} onClick={researchTop3}>{researchingIds.length ? `Researching ${researchingIds.length}…` : 'AI research top 3'}</button><button className="bg-teal-700 text-white rounded px-4 text-sm" disabled={searching} onClick={findProspects}>{searching ? 'Searching…' : 'Find Prospects'}</button></div>
    {notice && <p className="text-sm mb-3 text-teal-800">{notice}</p>}
    <div className="grid grid-cols-1 xl:grid-cols-[minmax(420px,1fr)_minmax(600px,1.2fr)] gap-4 h-[680px]"><section className="card overflow-hidden min-h-96"><ProspectMap prospects={list} selected={selected} onSelect={setSelected} /></section><section className="card overflow-auto"><table className="w-full"><thead className="sticky top-0 bg-white"><tr>{['Prospect signal', 'Facility', 'Type', 'City', 'Why it is listed', 'AI research', 'Contact', 'Status'].map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{list.map((prospect) => { const signals = signalFor(prospect); return <tr className={`cursor-pointer hover:bg-slate-50 ${selected?.id === prospect.id ? 'bg-teal-50' : ''}`} key={prospect.id} onClick={() => setSelected(prospect)}><td><span className={`score ${signals.score >= 65 ? 'score-high' : signals.score >= 40 ? 'score-mid' : 'score-low'}`}>{prospectSignalLabels[signals.tier]}</span></td><td className="font-medium">{prospect.name}</td><td className="capitalize">{label(prospect.facility_type)}</td><td>{prospect.city}</td><td>{signals.reasons.slice(0, 2).join(' · ') || 'Business listing'}</td><td className="capitalize">{prospect.ai_research?.grid_switch_fit ? `${prospect.ai_research.grid_switch_fit} fit` : prospect.ai_research_status === 'failed' ? 'Failed' : researchingIds.includes(prospect.id) ? 'Researching…' : 'Not researched'}</td><td>{prospect.phone && prospect.website ? 'Phone + site' : prospect.phone ? 'Phone' : prospect.website ? 'Website' : 'Unavailable'}</td><td className="capitalize">{prospect.prospect_status}</td></tr>; })}</tbody></table></section></div>
    {selected && selectedSignals && <aside className="fixed right-0 top-0 h-full w-[470px] bg-white shadow-2xl p-6 overflow-auto z-10"><button className="float-right text-slate-500" onClick={() => setSelected(null)}>Close</button><h2 className="text-xl font-bold pr-12">{selected.name}</h2><p className="mt-2"><span className="score score-high">{prospectSignalLabels[selectedSignals.tier]}</span> <span className="text-slate-600">Directory signal: {selectedSignals.score}/100</span></p><p className="text-sm mt-4">{selected.address}, {selected.city}, {selected.state} {selected.postal_code}</p><section className="mt-6"><h3 className="font-semibold">Why it surfaced</h3><ul className="mt-3 space-y-2 text-sm">{selectedSignals.reasons.map((reason) => <li key={reason} className="flex gap-2"><span className="text-teal-700">●</span>{reason}</li>)}</ul></section>{selected.ai_research && <AiResearch research={selected.ai_research} />}{!selected.ai_research && <section className="mt-6 rounded bg-teal-50 p-4 text-sm"><b>Need evidence beyond the directory?</b><p className="mt-1 text-slate-600">AI research searches public sources for facts tied to this exact location, then returns citations, an outreach angle, qualification questions, and explicit unknowns.</p></section>}<div className="flex gap-2 mt-6 flex-wrap"><button className="bg-teal-700 text-white rounded px-3 py-2 text-sm" disabled={isResearching} onClick={() => researchOne(selected)}>{isResearching ? 'Researching…' : selected.ai_research ? 'Refresh AI research' : 'Research this facility'}</button><button className="control" onClick={() => navigator.clipboard.writeText(`${selected.address}, ${selected.city}, ${selected.state}`)}>Copy address</button>{selected.phone && <a className="control" href={`tel:${selected.phone}`}>Call facility</a>}{selected.website && <a className="control" target="_blank" rel="noreferrer" href={selected.website}>Open website</a>}</div></aside>}
  </div></main>;
}
